[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' cdnjs.cloudflare.com fonts.googleapis.com; script-src 'self' https://cdnjs.cloudflare.com; style-src 'self' fonts.googleapis.com; font-src fonts.gstatic.com 'self'"
        X-Frame-Options = "DENY"
        X-Content-Type-Options = "nosniff"